const $=s=>document.querySelector(s);
const defaultTasks=[{id:'t1',title:'Finish DSA practice',priority:'High',done:false},{id:'t2',title:'Work on SIH project',priority:'Medium',done:false},{id:'t3',title:'Read a book (20 min)',priority:'Low',done:false},{id:'t4',title:'Workout',priority:'Low',done:false}];
const defaults={
 deepWork:{title:'Deep Work',render:()=>`<div class="timer-ring"><span id="focusMetric">25:00</span></div><button class="timer-btn" id="miniFocus">Start</button>`},
 github:{title:'GitHub',render:x=>`<div class="muted">Contribution activity</div><div class="heat">${(x?.levels||Array.from({length:48},(_,i)=>({level:[1,0,2,1,0,3,1,0][i%8]}))).slice(-48).map(v=>`<i class="${v.level>0?'on':''} ${v.level>2?'hot':''}"></i>`).join('')}</div><div class="streak">🔥 ${x?.streak??'—'} day streak</div>`},
 leetcode:{title:'LeetCode',render:x=>`<div class="muted">Daily activity</div><div class="heat">${(x?.levels||Array.from({length:48},(_,i)=>({level:[0,1,0,2,3,1,0,2,1,0,3,1][i%12]}))).slice(-48).map(v=>`<i class="${v.level>0?'on':''} ${v.level>2?'hot':''}"></i>`).join('')}</div><div class="streak">🔥 ${x?.streak??'—'} day streak</div>`},
 habits:{title:'Habits',render:()=>`<div class="habit"><span>Code</span><span class="rings">${[1,1,1,1,1,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div><div class="habit"><span>Read</span><span class="rings">${[1,1,1,0,0,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div><div class="habit"><span>Exercise</span><span class="rings">${[1,1,1,1,0,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div>`},
 upcoming:{title:'Upcoming',render:events=>events?.length?events.slice(0,3).map(e=>`<div class="event"><span class="time">${e.time}</span><span>${e.title}</span></div>`).join(''):`<div class="empty">Connect Google Calendar in Settings.</div>`}
};
function timeKey(h){return h<5?'night':h<12?'morning':h<17?'afternoon':h<22?'evening':'night'}
function background(){return "url('assets/lifeos-times.webp')"}
function backgroundPosition(key){return ({morning:'left top',afternoon:'right top',evening:'left bottom',night:'right bottom'})[key]||'right bottom'}
async function loadIntegrationStats(integrations){const result={};if(integrations?.github){try{const r=await chrome.runtime.sendMessage({type:'GITHUB_STATS',username:integrations.github});if(r?.ok)result.github=r.data}catch(e){console.warn(e)}}if(integrations?.leetcode){try{const r=await chrome.runtime.sendMessage({type:'LEETCODE_STATS',username:integrations.leetcode});if(r?.ok)result.leetcode=r.data}catch(e){console.warn(e)}}return result}
async function loadTasks(){const d=await chrome.storage.local.get('tasks');if(!Array.isArray(d.tasks)){await chrome.storage.local.set({tasks:defaultTasks});return defaultTasks}return d.tasks}
function taskHTML(tasks){return tasks.map(t=>`<div class="task ${t.done?'done':''}" data-task="${t.id}"><button class="check" data-toggle="${t.id}" aria-label="Mark task complete">${t.done?'✓':''}</button><span class="task-title" data-edit="${t.id}">${escapeHtml(t.title)}</span><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span></div>`).join('')||`<div class="empty">No tasks yet. Add one below.</div>`}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function renderTasks(){const tasks=await loadTasks();$('#taskList').innerHTML=taskHTML(tasks);document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.dataset.toggle;const d=await chrome.storage.local.get('tasks');const list=d.tasks||[];const t=list.find(x=>x.id===id);if(t){t.done=!t.done;await chrome.storage.local.set({tasks:list});renderTasks()}});document.querySelectorAll('[data-edit]').forEach(el=>el.onclick=async()=>{const id=el.dataset.edit;const d=await chrome.storage.local.get('tasks');const list=d.tasks||[];const t=list.find(x=>x.id===id);if(!t)return;const next=prompt('Edit task',t.title);if(next!==null&&next.trim()){t.title=next.trim();await chrome.storage.local.set({tasks:list});renderTasks()}})}
async function addTask(){const title=prompt('New task');if(!title?.trim())return;const priority=prompt('Priority: High, Medium, or Low','Medium')||'Medium';const d=await chrome.storage.local.get('tasks');const list=Array.isArray(d.tasks)?d.tasks:[];list.push({id:`t-${Date.now()}`,title:title.trim(),priority:['High','Medium','Low'].includes(priority)?priority:'Medium',done:false});await chrome.storage.local.set({tasks:list});renderTasks()}
async function render(){const d=await chrome.storage.local.get(['widgets','themeSettings','focusSession','integrations','calendarEvents']);const widgets=d.widgets||['deepWork','github','leetcode','habits','upcoming'];const theme=d.themeSettings||{backgroundMode:'time'};const scene=$('#scene');if(theme.backgroundMode==='custom'&&theme.customBackground){scene.style.backgroundImage=`url(${theme.customBackground})`;scene.style.backgroundSize='cover';scene.style.backgroundPosition='center'}else{const key=timeKey(new Date().getHours());scene.style.backgroundImage=background(key);scene.style.backgroundSize='200% 200%';scene.style.backgroundPosition=backgroundPosition(key)}const stats=await loadIntegrationStats(d.integrations);const events=(d.calendarEvents||[]).map(e=>({title:e.summary||'Untitled event',time:e.start?.dateTime?new Date(e.start.dateTime).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'All day'}));$('#widgetGrid').innerHTML=widgets.map(id=>defaults[id]?`<article class="card"><h3>${defaults[id].title}</h3>${defaults[id].render(id==='github'?stats.github:id==='leetcode'?stats.leetcode:id==='upcoming'?events:null)}</article>`:'').join('');await renderTasks();updateFocus(d.focusSession)}
function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString([], {weekday:'long',month:'short',day:'2-digit'}).toUpperCase();const h=d.getHours();$('#greeting').textContent=(h<12?'Good Morning':h<17?'Good Afternoon':h<22?'Good Evening':'Good Night')+'\nLet’s make it count.'}
function updateFocus(s){const m=$('#focusMetric');if(!m)return;const left=s?.active?Math.max(0,s.endsAt-Date.now()):25*60000;m.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor(left/1000)%60).padStart(2,'0')}`}
$('#focusBtn').onclick=()=>location.href='focus.html';$('#settingsBtn').onclick=()=>chrome.runtime.openOptionsPage();$('#addTaskBtn').onclick=addTask;$('#inlineAdd').onclick=addTask;$('#journalBtn').onclick=()=>alert('Journal is ready for the next module.');$('#noteBtn').onclick=()=>{const n=prompt('Quick note');if(n?.trim())chrome.storage.local.set({quickNote:n.trim()})};$('#seeTasks').onclick=()=>alert('Task management is available directly on this dashboard. Click a task title to edit it.');document.addEventListener('click',e=>{const b=e.target.closest('.timer-btn');if(b)location.href='focus.html';const shortcut=e.target.closest('[data-url]');if(shortcut)location.href=shortcut.dataset.url;});$('#addShortcut').onclick=()=>{const url=prompt('Website URL');if(url?.trim())location.href=url.startsWith('http')?url:'https://'+url};$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(q)location.href=`https://www.google.com/search?q=${encodeURIComponent(q)}`}});updateClock();setInterval(()=>{updateClock();chrome.storage.local.get('focusSession').then(x=>updateFocus(x.focusSession))},1000);chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&(changes.widgets||changes.themeSettings||changes.integrations||changes.calendarEvents||changes.tasks))render()});render();