const $ = s => document.querySelector(s);
const defaults = {
  deepWork: { title:'Deep Work', render:()=>`<div class="metric"><div><div class="muted">Focus session</div><strong id="focusMetric">Ready</strong></div><span class="muted">25 min</span></div><div class="muted" style="margin-top:15px">Choose a profile to restrict your browser to intentional work.</div>` },
  github: { title:'GitHub', render:()=>`<div class="metric"><div><div class="muted">Contribution activity</div><strong>24</strong></div><span class="muted">this year</span></div><div class="heat">${Array.from({length:48},(_,i)=>`<i class="${i%4!==0?'on':''}"></i>`).join('')}</div>` },
  habits: { title:'Habits', render:()=>`<div class="habit"><span>Code</span><span class="rings">${[1,1,1,1,1,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div><div class="habit"><span>Read</span><span class="rings">${[1,1,1,0,0,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div><div class="habit"><span>Exercise</span><span class="rings">${[1,1,1,1,0,0,0].map(x=>`<i class="ring ${x?'done':''}"></i>`).join('')}</span></div>` },
  upcoming: { title:'Upcoming', render:()=>`<div class="event"><span class="time">16:00</span><span>Project meeting</span></div><div class="event"><span class="time">18:30</span><span>Gym</span></div><div class="event"><span class="time">20:00</span><span>Study session</span></div>` },
  leetcode: { title:'LeetCode', render:()=>`<div class="metric"><div><div class="muted">Daily streak</div><strong>7</strong></div><span class="muted">days</span></div><div class="muted" style="margin-top:16px">Connect your username in Settings.</div>` },
  tasks: { title:'Today', render:()=>`<div class="task"><span class="check"></span>Finish project architecture <span class="badge">HIGH</span></div><div class="task"><span class="check"></span>Practice 2 DSA problems</div><div class="task"><span class="check"></span>Review pull requests</div>` }
};
function timeKey(h){return h<5?'night':h<12?'morning':h<17?'afternoon':h<22?'evening':'night'}
function background(key){const svg={morning:'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#6e8db6"/><stop offset=".5" stop-color="#f4b477"/><stop offset="1" stop-color="#3e536d"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="1250" cy="210" r="110" fill="#ffe0a0" opacity=".8"/><path d="M0 650L350 420 650 650 900 380 1250 650 1500 450 1600 600V900H0Z" fill="#243344" opacity=".72"/></svg>',afternoon:'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#5f7f9d"/><stop offset=".55" stop-color="#d49a72"/><stop offset="1" stop-color="#242b3c"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="1050" cy="240" r="90" fill="#ffe6b1" opacity=".65"/><path d="M0 690L300 500 540 670 850 430 1160 670 1430 470 1600 620V900H0Z" fill="#283342" opacity=".8"/></svg>',evening:'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#161c38"/><stop offset=".5" stop-color="#9b4d72"/><stop offset="1" stop-color="#1a2030"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="1250" cy="260" r="100" fill="#ffb37d" opacity=".55"/><path d="M0 700L350 470 650 670 900 410 1250 670 1500 450 1600 610V900H0Z" fill="#101725" opacity=".9"/></svg>',night:'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#070b18"/><stop offset=".5" stop-color="#172449"/><stop offset="1" stop-color="#090d19"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="1250" cy="190" r="80" fill="#dce6ff" opacity=".75"/><path d="M0 700L350 460 650 680 900 430 1250 680 1500 470 1600 610V900H0Z" fill="#060b15" opacity=".95"/><g fill="#fff" opacity=".5">${Array.from({length:30},(_,i)=>`<circle cx="${(i*137)%1550}" cy="${70+(i*53)%420}" r="1.5"/>`).join('')}</g></svg>'}; return `url("data:image/svg+xml,${encodeURIComponent(svg[key])}")`}
async function render(){
  const data=await chrome.storage.local.get(['widgets','themeSettings','focusSession']);
  const widgets=data.widgets||['deepWork','github','habits','upcoming'];
  const theme=data.themeSettings||{backgroundMode:'time'};
  const scene=$('#scene');
  scene.style.backgroundImage=theme.backgroundMode==='custom'&&theme.customBackground?`url(${theme.customBackground})`:background(timeKey(new Date().getHours()));
  $('#widgetGrid').innerHTML=widgets.map(id=>defaults[id]?`<article class="card"><h3>${defaults[id].title}</h3>${defaults[id].render()}</article>`:'').join('');
  updateFocus(data.focusSession);
}
function updateClock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString([], {weekday:'long',month:'short',day:'2-digit'}).toUpperCase()}
function updateFocus(session){const metric=$('#focusMetric');if(!metric)return;if(!session?.active){metric.textContent='Ready';return} const left=Math.max(0,session.endsAt-Date.now()); metric.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor(left/1000)%60).padStart(2,'0')}`;if(left<=0)render()}
$('#focusBtn').onclick=()=>location.href='focus.html';$('#settingsBtn').onclick=()=>chrome.runtime.openOptionsPage();$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(q)location.href=`https://www.google.com/search?q=${encodeURIComponent(q)}`}});
updateClock();setInterval(()=>{updateClock();chrome.storage.local.get('focusSession').then(x=>updateFocus(x.focusSession))},1000);render();
